spring:
  application:
    name: Hotelbooking   # ✅ App name

  data:
    mongodb:
      uri: ${MONGO_URI}   # ✅ Your MongoDB connection string
      auto-index-creation: true

  security:
    user:
      name: ${SPRING_SECURITY_USER}     # ✅ Admin username (from env var)
      password: ${SPRING_SECURITY_PASSWORD} # ✅ Admin password (from env var)

  servlet:
    multipart:
      max-file-size: 5MB      # ✅ Upload file limit
      max-request-size: 5MB

  web:
    resources:
      static-locations: file:uploads/  # ✅ Serve uploaded images/files

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}     # ✅ Gmail/SMTP user (from env var)
    password: ${MAIL_PASSWORD}     # ✅ Gmail/SMTP app password (from env var)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

google:
  recaptcha:
    secret: ${GOOGLE_RECAPTCHA_SECRET}   # ✅ Recaptcha secret (from env var)

server:
  port: ${PORT:8080}   # ✅ Use provided port (needed for Render/Railway)

jwt:
  secret: ${JWT_SECRET}            # ✅ JWT secret (from env var)
  expiration: ${JWT_EXPIRATION:86400000} # ✅ 1 day default
